In [1]:
import funciones as fs

In [2]:
df = fs.leer_dataframe("Berlin_Alemania.csv")
df

,Unnamed: 0,id,scrape_id,name,description,host_id,host_name,host_is_superhost,host_listings_count,host_total_listings_count,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,2084992,20241221052002,"Nice and cozy apartment in Kreuzberg, Graefekiez",Our cosy two room Apartment (70qm) in a vibrat...,6302373,Andreas,f,1.0,1.0,...,5.00,4.64,4.82,NaN,f,1,1,0,0,0.09
1,1,1123383729460847373,20241221052002,Furnished room in well equipped serviced apart...,Room in an apartment available. Apartment has ...,206488801,Supriya,f,7.0,7.0,...,NaN,NaN,NaN,NaN,f,3,1,2,0,NaN
2,2,1205255838613758737,20241221052002,Luxurous game room with private bath in X-Berg,Cozy private room in Berlin Mitte with private...,50009901,Gabriel,t,1.0,1.0,...,4.97,4.94,4.94,01/Z/AZ/017416-24,f,1,0,1,0,9.53
3,3,8164759,20241221052002,Beautiful single-room studio,Experience the “real Berlin” in our small and ...,42115726,Lars,f,1.0,3.0,...,5.00,3.00,3.00,NaN,f,1,1,0,0,0.01
4,4,18836877,20241221052002,Unterkunft zentral in Berlin,"The accommodation has 3 rooms, however, is onl...",131184702,Jana,f,1.0,1.0,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13979,13979,1066742710842868324,20241221052002,Cozy bedroom in a stylish house,NaN,125006999,Sophie,t,3.0,3.0,...,5.00,4.78,5.00,03/Z/AZ/007577-22,f,3,0,3,0,0.82
13980,13980,882524735229064604,20241221052002,hornos - 1 bedroom apartment in kreuzberg,"Spectacular apartment in Eylauerstrasse, with ...",449692327,Ukio Germany,f,58.0,59.0,...,NaN,NaN,NaN,NaN,t,58,58,0,0,NaN
13981,13981,1172288594718636022,20241221052002,Deluxe Superior Accessible,This wheelchair accessible double room feature...,570785536,Sergio,f,6.0,6.0,...,NaN,NaN,NaN,Legal entity name and Legal form: Bellman Hote...,t,6,0,6,0,NaN
13982,13982,1233927040956879330,20241221052002,Prenzlauerberg Berlin,Fully equipped apartment with large balcony in...,3893392,Nikolaj,f,2.0,2.0,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
13983,13983,1285513092900098347,20241221052002,Charmant appart berlinois,Enjoy with your family this great place to sta...,21907458,Inès Lily,f,1.0,1.0,...,NaN,NaN,NaN,First name and Last name: Ines Chebli <br/> Co...,f,1,1,0,0,NaN

In [3]:
df = df.drop(columns=["Unnamed: 0"]) #eliminar columna sobrante

In [4]:
df = fs.sustituir_valores_nulos(df) #sustituir nulos
df

,id,host_id,host_total_listings_count,longitude,bathrooms,beds,minimum_nights,minimum_minimum_nights,minimum_maximum_nights,minimum_nights_avg_ntm,...,review_scores_location,calculated_host_listings_count,calculated_host_listings_count_private_rooms,reviews_per_month,description,host_name,host_has_profile_pic,property_type,price,license
0,2084992,6302373,1.0,13.414800,1.2,2.0,92,92,1125,92.0,...,4.64,1,0,0.09,Our cosy two room Apartment (70qm) in a vibrat...,Andreas,t,Entire rental unit,Este es un valor nulo,Este es un valor nulo
1,1123383729460847373,206488801,7.0,13.350000,0.5,1.0,93,93,365,93.0,...,99.00,3,2,99.00,Room in an apartment available. Apartment has ...,Supriya,t,Private room in rental unit,$117.00,Este es un valor nulo
2,1205255838613758737,50009901,1.0,13.415324,1.0,1.0,1,1,1125,1.0,...,4.94,1,1,9.53,Cozy private room in Berlin Mitte with private...,Gabriel,t,Private room in condo,$95.00,01/Z/AZ/017416-24
3,8164759,42115726,3.0,13.357780,1.2,2.0,92,92,1125,92.0,...,3.00,1,0,0.01,Experience the “real Berlin” in our small and ...,Lars,t,Entire rental unit,Este es un valor nulo,Este es un valor nulo
4,18836877,131184702,1.0,13.420490,1.2,2.0,92,92,1125,92.0,...,99.00,1,0,99.00,"The accommodation has 3 rooms, however, is onl...",Jana,t,Entire rental unit,Este es un valor nulo,Este es un valor nulo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13979,1066742710842868324,125006999,3.0,13.460553,1.2,2.0,1,1,365,6.1,...,4.78,3,3,0.82,Este es un valor nulo,Sophie,t,Private room in home,Este es un valor nulo,03/Z/AZ/007577-22
13980,882524735229064604,449692327,59.0,13.375470,1.0,1.0,92,92,330,92.0,...,99.00,58,0,99.00,"Spectacular apartment in Eylauerstrasse, with ...",Ukio Germany,t,Entire rental unit,$64.00,Este es un valor nulo
13981,1172288594718636022,570785536,6.0,13.444353,1.2,2.0,1,1,365,1.3,...,99.00,6,6,99.00,This wheelchair accessible double room feature...,Sergio,t,Room in hotel,Este es un valor nulo,Legal entity name and Legal form: Bellman Hote...
13982,1233927040956879330,3893392,2.0,13.440550,1.2,2.0,92,92,365,92.0,...,99.00,2,0,99.00,Fully equipped apartment with large balcony in...,Nikolaj,t,Entire rental unit,Este es un valor nulo,Este es un valor nulo
13983,1285513092900098347,21907458,1.0,13.344286,1.0,1.0,120,120,150,120.0,...,99.00,1,0,99.00,Enjoy with your family this great place to sta...,Inès Lily,t,Entire rental unit,$65.00,First name and Last name: Ines Chebli <br/> Co...

In [5]:
fs.identificar_nulos(df) #contar si funcionó

('Valores nulos por columna',
 id                                              0
 host_id                                         0
 host_total_listings_count                       0
 longitude                                       0
 bathrooms                                       0
 beds                                            0
 minimum_nights                                  0
 minimum_minimum_nights                          0
 minimum_maximum_nights                          0
 minimum_nights_avg_ntm                          0
 availability_60                                 0
 availability_365                                0
 number_of_reviews_ltm                           0
 review_scores_rating                            0
 review_scores_cleanliness                       0
 review_scores_communication                     0
 review_scores_value                             0
 calculated_host_listings_count_entire_homes     0
 calculated_host_listings_count_shared_rooms     0
 name                                            0
 host_is_superhost                               0
 host_identity_verified                          0
 room_type                                       0
 has_availability                                0
 instant_bookable                                0
 scrape_id                                       0
 host_listings_count                             0
 latitude                                        0
 accommodates                                    0
 bedrooms                                        0
 maximum_nights                                  0
 maximum_minimum_nights                          0
 maximum_maximum_nights                          0
 maximum_nights_avg_ntm                          0
 availability_30                                 0
 availability_90                                 0
 number_of_reviews                               0
 number_of_reviews_l30d                          0
 review_scores_accuracy                          0
 review_scores_checkin                           0
 review_scores_location                          0
 calculated_host_listings_count                  0
 calculated_host_listings_count_private_rooms    0
 reviews_per_month                               0
 description                                     0
 host_name                                       0
 host_has_profile_pic                            0
 property_type                                   0
 price                                           0
 license                                         0
 dtype: int64,
 'valores nulos por dataframe',
 np.int64(0))

In [6]:
data_sin_atipicos= fs.identificar_valores_atipicos2(df)

id                                                 0
host_id                                            0
host_total_listings_count                       1955
longitude                                        565
bathrooms                                       1054
beds                                            1102
minimum_nights                                    42
minimum_minimum_nights                            39
minimum_maximum_nights                            11
minimum_nights_avg_ntm                            41
availability_60                                    0
availability_365                                   0
number_of_reviews_ltm                           1812
review_scores_rating                            1105
review_scores_cleanliness                       1082
review_scores_communication                      720
review_scores_value                             1104
calculated_host_listings_count_entire_homes     2129
calculated_host_listings_count_shared_rooms       96
scrape_id                                          0
host_listings_count                             2180
latitude                                         401
accommodates                                     456
bedrooms                                        2311
maximum_nights                                     3
maximum_minimum_nights                           308
maximum_maximum_nights                            13
maximum_nights_avg_ntm                            13
availability_30                                    0
availability_90                                    0
number_of_reviews                               1879
number_of_reviews_l30d                          3088
review_scores_accuracy                          4144
review_scores_checkin                           4361
review_scores_location                          4065
calculated_host_listings_count                  2398
calculated_host_listings_count_private_rooms     951
reviews_per_month                               3301
dtype: int64

In [ ]:
fs.identificar_nulos(data_sin_atipicos) #consultar si ya no hay valores atipicos

('Valores nulos por columna',
 name                                            0
 host_is_superhost                               0
 host_identity_verified                          0
 room_type                                       0
 has_availability                                0
 instant_bookable                                0
 description                                     0
 host_name                                       0
 host_has_profile_pic                            0
 property_type                                   0
 price                                           0
 license                                         0
 id                                              0
 host_id                                         0
 host_total_listings_count                       0
 longitude                                       0
 bathrooms                                       0
 beds                                            0
 minimum_nights                                  0
 minimum_minimum_nights                          0
 minimum_maximum_nights                          0
 minimum_nights_avg_ntm                          0
 availability_60                                 0
 availability_365                                0
 number_of_reviews_ltm                           0
 review_scores_rating                            0
 review_scores_cleanliness                       0
 review_scores_communication                     0
 review_scores_value                             0
 calculated_host_listings_count_entire_homes     0
 calculated_host_listings_count_shared_rooms     0
 scrape_id                                       0
 host_listings_count                             0
 latitude                                        0
 accommodates                                    0
 bedrooms                                        0
 maximum_nights                                  0
 maximum_minimum_nights                          0
 maximum_maximum_nights                          0
 maximum_nights_avg_ntm                          0
 availability_30                                 0
 availability_90                                 0
 number_of_reviews                               0
 number_of_reviews_l30d                          0
 review_scores_accuracy                          0
 review_scores_checkin                           0
 review_scores_location                          0
 calculated_host_listings_count                  0
 calculated_host_listings_count_private_rooms    0
 reviews_per_month                               0
 dtype: int64,
 'valores nulos por dataframe',
 np.int64(0))

In [9]:
data_sin_atipicos.to_csv("Berlin_procesado.csv") #pasar a un nuevo csv